# Generated by Django 4.0.3 on 2022-04-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premise',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='premise',
            old_name='Name',
            new_name='name',
        ),
    ]
